PDB-567 Introduce latest commons-compress
Previous versions of commons-compress were introducing an exception during
archival:

Writing report '2014-04-03T08:44:43.158Z-heads/production-0-g6e18d80' for node 'XXXXXXXXXXXXXXXXXXXX'
java.io.IOException: This archives contains unclosed entries.
 at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.finish (TarArchiveOutputStream.java:214)
    org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.close (TarArchiveOutputStream.java:229)
    sun.reflect.NativeMethodAccessorImpl.invoke0 (NativeMethodAccessorImpl.java:-2)
    sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:57)

The latest version does not.

Signed-off-by: Ken Barber <ken@bob.sh>